import Head from 'next/head'

import SiteHeader from '../src/components/Header/SiteHeader';

import styles from '../src/styles/Pages/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SiteHeader />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to MY APP!
        </h1>
      </main>

      <footer className={styles.footer}>
        <span>footer</span>
      </footer>
    </div>
  )
}
